### ISSUE TITLE
Type inference ignores unreachable code

### ISSUE THREAD

**Issue by myreen** [CakeML/pure#27]
Surprisingly the compiler accepts:
```
foo n = if n + () then () else ()

main = Ret ()
```

While it rejects the following:
```
foo n = if n + () then () else ()

main = Ret (foo 5)
```

**Comment by hrutvik** [comment]
Currently, `letrec` transformations [happen before](https://github.com/CakeML/pure/blob/de95119f4eb461ad5a1e73a72fe056b6da7beaa1/compiler/pure_compilerScript.sml#L40-L41) type inference, removing such unreachable top-level declarations before inference sees them. I believe we chose this ordering due to a lack of type signature support (#25), which makes it more efficient to untangle `letrec`s before attempting to infer their types from scratch. We can reorder inference/transformation provided we prove that the `letrec` transformations preserve typing, at a (small?) loss of efficiency until type signatures are supported.

**Comment by hrutvik** [comment]
As discussed in a meeting, we have decided to:
- topologically sort `letrec`s and convert non-recursive ones into `let`s **before** type inference (as before)
- move the pass which deletes unreachable `letrec`s **after** type inference

This ensures that dead code will still be type-checked, but removed before demands analysis. We will need to prove that deletion of unreachable `letrec`s preserves typing. We should also be able to prove that the passes before type inference preserve free variables, so that the parser no longer needs to [check for closedness](https://github.com/CakeML/pure/blob/88b4dcd419fe255f9b4e678d554527d6f34ac62b/compiler/parsing/pureParseScript.sml#L55).
